version: '3'

services:
  web:
    build: .
    ports:
      - "4567:4567"
    volumes:
      - .:/app
      - gem_cache:/gems
    environment:
      - RACK_SESSION_SECRET='really_really_really_really_really_really_long_rack_cookie_secret'
    env_file:
      - .env

volumes:
  gem_cache:
